import type { FlowGraphDefinition, FlowNodeDefinition, FlowPipelineDefinition } from './types';

export const FLOW_PIPELINES: FlowPipelineDefinition[] = [
  {
    key: 'setup_validation',
    label: 'Setup Validation',
    description: '프로젝트 연결과 인증 상태를 확인합니다.',
    accent: '#1d4ed8',
  },
  {
    key: 'member_resolution',
    label: 'Member Resolution',
    description: '프로젝트 멤버 후보와 매핑 범위를 검증합니다.',
    accent: '#0f766e',
  },
  {
    key: 'identity_integrity',
    label: 'Identity Integrity',
    description: '식별자 매칭과 중복 병합 위험을 점검합니다.',
    accent: '#a16207',
  },
  {
    key: 'snapshot_sync',
    label: 'Snapshot Sync',
    description: 'Jira / GitLab 스냅샷 수집 경로를 검증합니다.',
    accent: '#7c3aed',
  },
  {
    key: 'analytics_build',
    label: 'Analytics Build',
    description: '점수 계산과 요약 뷰를 재구성합니다.',
    accent: '#c2410c',
  },
  {
    key: 'read_verification',
    label: 'Read Verification',
    description: '대시보드와 개발자 상세 조회 경로를 확인합니다.',
    accent: '#be123c',
  },
];

export const FLOW_NODES: FlowNodeDefinition[] = [
  {
    key: 'project_connection_check',
    label: 'Project Connection Check',
    description: '저장된 Jira / GitLab 프로젝트의 연결 테스트를 순회합니다.',
    pipelineKey: 'setup_validation',
    serviceKey: 'projectConnectionCheck',
    targetType: 'project',
    dependsOn: [],
    x: 80,
    y: 220,
  },
  {
    key: 'member_candidates_fetch',
    label: 'Member Candidates Fetch',
    description: '프로젝트별 멤버 후보를 실제 API로 조회합니다.',
    pipelineKey: 'member_resolution',
    serviceKey: 'memberCandidatesFetch',
    targetType: 'project',
    dependsOn: ['project_connection_check'],
    x: 430,
    y: 220,
  },
  {
    key: 'mapping_scope_validate',
    label: 'Mapping Scope Validate',
    description: '저장된 projectDeveloper 범위와 매핑 수를 검증합니다.',
    pipelineKey: 'member_resolution',
    serviceKey: 'mappingScopeValidate',
    targetType: 'workspace',
    dependsOn: ['member_candidates_fetch'],
    x: 780,
    y: 220,
  },
  {
    key: 'identity_match_audit',
    label: 'Identity Match Audit',
    description: '매칭 점수와 미매칭 후보를 점검합니다.',
    pipelineKey: 'identity_integrity',
    serviceKey: 'identityMatchAudit',
    targetType: 'workspace',
    dependsOn: ['mapping_scope_validate'],
    x: 1130,
    y: 60,
  },
  {
    key: 'duplicate_merge_audit',
    label: 'Duplicate Merge Audit',
    description: '중복 개발자 후보와 auto-merge 위험을 검사합니다.',
    pipelineKey: 'identity_integrity',
    serviceKey: 'duplicateMergeAudit',
    targetType: 'workspace',
    dependsOn: ['mapping_scope_validate'],
    x: 1130,
    y: 380,
  },
  {
    key: 'jira_snapshot_sync',
    label: 'Jira Snapshot Sync',
    description: 'Jira 프로젝트 동기화와 스냅샷 건수를 검증합니다.',
    pipelineKey: 'snapshot_sync',
    serviceKey: 'jiraSnapshotSync',
    targetType: 'project',
    dependsOn: ['identity_match_audit', 'duplicate_merge_audit'],
    x: 1480,
    y: 60,
  },
  {
    key: 'gitlab_snapshot_sync',
    label: 'GitLab Snapshot Sync',
    description: 'GitLab 프로젝트 동기화와 스냅샷 건수를 검증합니다.',
    pipelineKey: 'snapshot_sync',
    serviceKey: 'gitlabSnapshotSync',
    targetType: 'project',
    dependsOn: ['identity_match_audit', 'duplicate_merge_audit'],
    x: 1480,
    y: 380,
  },
  {
    key: 'score_recompute',
    label: 'Score Recompute',
    description: '현재 기간 점수를 재평가하고 결과를 확인합니다.',
    pipelineKey: 'analytics_build',
    serviceKey: 'scoreRecompute',
    targetType: 'workspace',
    dependsOn: ['jira_snapshot_sync', 'gitlab_snapshot_sync'],
    x: 1830,
    y: 60,
  },
  {
    key: 'summary_view_refresh_verify',
    label: 'Summary View Refresh Verify',
    description: 'dashboard summary 경로를 재조회해 평균값을 확인합니다.',
    pipelineKey: 'analytics_build',
    serviceKey: 'summaryViewRefreshVerify',
    targetType: 'workspace',
    dependsOn: ['score_recompute'],
    x: 1830,
    y: 380,
  },
  {
    key: 'dashboard_insights_verify',
    label: 'Dashboard Insights Verify',
    description: '대시보드 요약, 랭킹, 개발자 카드가 읽히는지 점검합니다.',
    pipelineKey: 'read_verification',
    serviceKey: 'dashboardInsightsVerify',
    targetType: 'workspace',
    dependsOn: ['summary_view_refresh_verify'],
    x: 2180,
    y: 60,
  },
  {
    key: 'developer_detail_verify',
    label: 'Developer Detail Verify',
    description: '티켓/MR/공수 조회 경로가 실제 데이터와 함께 열리는지 확인합니다.',
    pipelineKey: 'read_verification',
    serviceKey: 'developerDetailVerify',
    targetType: 'developer',
    dependsOn: ['dashboard_insights_verify'],
    x: 2180,
    y: 380,
  },
];

export const CORE_BUSINESS_FLOW: FlowGraphDefinition = {
  pipelines: FLOW_PIPELINES,
  nodes: FLOW_NODES,
  edges: FLOW_NODES.flatMap((node) => node.dependsOn.map((dependency) => ({ from: dependency, to: node.key }))),
};

export const FLOW_NODE_BY_KEY = new Map(CORE_BUSINESS_FLOW.nodes.map((node) => [node.key, node] as const));
